### PR TITLE
update @stoplight/scripts

### PR DESCRIPTION
**Pull request by marbemac**
Notes in the commits.

Note: tests won't pass in CI until we publish graph I guess.

### CODE REVIEW

**Comment by billiegoose** [comment]
blocked by #2 because I wound back develop so vincenzo could review. will merge afterwards

**Comment by billiegoose** [comment]
@marbemac what did you do to my test coverage lol

```
---------------------------|----------|----------|----------|----------|-------------------|
File                       |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------------|----------|----------|----------|----------|-------------------|
All files                  |       29 |       35 |     8.72 |    30.14 |                   |
 src                       |    88.89 |     87.5 |       65 |    89.19 |                   |
  DraftValue.tsx           |       20 |        0 |        0 |       20 |... 30,33,34,35,39 |
  Formtron.tsx             |       50 |      100 |        0 |       50 | 18,21,22,23,27,28 |
  applyOps.ts              |      100 |      100 |      100 |      100 |                   |
  computeOps.ts            |    98.11 |    88.89 |      100 |    98.04 |                19 |
  computeWarnings.ts       |      100 |      100 |      100 |      100 |                   |
  deriveFormData.ts        |       95 |    86.36 |      100 |    97.44 |                63 |
  fieldName.ts             |      100 |      100 |      100 |      100 |                   |
 src/__stories__           |        0 |        0 |        0 |        0 |                   |
  Defer.tsx                |        0 |        0 |        0 |        0 |... 14,17,18,19,21 |
  FormtronDebugger.tsx     |        0 |        0 |        0 |        0 |... 27,128,129,130 |
  State.tsx                |        0 |      100 |        0 |        0 |  1,12,14,15,20,23 |
  autocompletionSources.ts |        0 |        0 |        0 |        0 |... 14,15,20,23,45 |
  customWidgets.tsx        |        0 |      100 |        0 |        0 |     1,5,7,9,15,17 |
  initGraph.ts             |        0 |        0 |        0 |        0 |... 48,50,51,52,54 |
  stories-graph.tsx        |        0 |        0 |        0 |        0 |... 52,53,54,59,61 |
  stories.tsx              |        0 |      100 |        0 |        0 |... 46,53,64,71,78 |
 src/components            |        0 |        0 |        0 |        0 |                   |
  AutocompletionContext.ts |        0 |      100 |      100 |        0 |              1,13 |
  DraftValue.tsx           |        0 |        0 |        0 |        0 |... 30,33,34,35,39 |
  advanced.tsx             |        0 |        0 |        0 |        0 |... 38,45,52,54,55 |
  basic.tsx                |        0 |        0 |        0 |        0 |... 23,229,235,239 |
  complex.tsx              |        0 |        0 |        0 |        0 |... 42,143,144,145 |
 src/components/utils      |        0 |        0 |        0 |        0 |                   |
  ThrottleValue.tsx        |        0 |        0 |        0 |        0 |... 21,22,23,28,31 |
---------------------------|----------|----------|----------|----------|-------------------|
```

Edit: To be fair I rebased your PR so it could have been me

**Review by billiegoose — APPROVED** [review]
Other than the test coverage plummet it looks good! 👍

**Comment by marbemac** [comment]
Arg, `__stories__` should be ignored when calculating coverage! Will check that out real quick before merging.

**Comment by marbemac** [comment]
Merged - coverage no longer collects from __stories__ folder. Should it have been higher even without the stories folder? Not sure what it was before.

**Comment by billiegoose** [comment]
The only files not covered are `.tsx` files - shouldn't those be ignored too since we're no longer snapshot testing?

**Comment by billiegoose** [comment]
Aha! Here's the output from before this PR for reference:
```
---------------------------|----------|----------|----------|----------|-------------------|
File                       |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------------|----------|----------|----------|----------|-------------------|
All files                  |    96.24 |    90.32 |      100 |    96.88 |                   |
 src                       |    97.71 |    90.32 |      100 |    98.41 |                   |
  applyOps.ts              |      100 |      100 |      100 |      100 |                   |
  computeOps.ts            |    98.11 |    88.89 |      100 |    98.04 |                19 |
  computeWarnings.ts       |      100 |      100 |      100 |      100 |                   |
  deriveFormData.ts        |       95 |    86.36 |      100 |    97.44 |                63 |
  fieldName.ts             |      100 |      100 |      100 |      100 |                   |
 src/components            |        0 |      100 |      100 |        0 |                   |
  AutocompletionContext.ts |        0 |      100 |      100 |        0 |              1,13 |
---------------------------|----------|----------|----------|----------|-------------------|
```

**Pull request merged**
