### PR TITLE
fix: background of +/- icon buttons should be transparent

### PR DESCRIPTION
**Pull request by billiegoose**
image

### CODE REVIEW

**Comment by casserni** [comment]
@wmhilton can you also fix the hover and active colors?

https://cl.ly/05500524a6f8

**Comment by billiegoose** [comment]
@casserni oooh. how do I do that?

**Comment by billiegoose** [comment]
lol

**Comment by casserni** [comment]
```
css= {
  ':active': {
    border: 'transparent',
  },
  ':hover': {
    background: 'hsla(0,0%,0%,0.05)!important'
  },
};

```

**Comment by billiegoose** [comment]
@casserni what do you think of this for hover & active?

**Comment by billiegoose** [comment]
fun fact: setting `border="transparent"` is invalid CSS apparently... which makes the border go _away_ not make it transparent! which is why we were getting this fun jiggle when `:active` turned the border back on

**Review by casserni — APPROVED** [review]

**Pull request merged**
